version: 2.1

jobs:
    tests-php-cs:
        docker:
            - image: php:8.0-cli-alpine
        steps:
            - checkout
            - run: wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.19.0/php-cs-fixer.phar
            - run: php php-cs-fixer.phar fix --dry-run --diff

    tests-phpunit:
        parameters:
            php-version:
                type: string
        docker:
            - image: circleci/php:<< parameters.php-version >>
        steps:
            - run: sudo composer self-update

            - checkout

            # Dependencies
            - restore_cache:
                  key: v1-deps-{{ checksum "composer.json" }}
            - run: composer install
            - save_cache:
                  paths: [ ./vendor ]
                  key: v1-deps-{{ checksum "composer.json" }}

            # Install PHPUnit
            - restore_cache:
                  key: v1-phpunit-{{ checksum "composer.json" }}
            - run: php vendor/bin/simple-phpunit install
            - save_cache:
                  paths: [ ./bin/.phpunit ]
                  key: v1-phpunit-{{ checksum "composer.json" }}

            # Run the tests
            - run: php vendor/bin/simple-phpunit -v --log-junit ./phpunit/junit.xml
            - store_test_results:
                  path: ./phpunit

    release:
        docker:
            - image: circleci/php:7.1
        steps:
            - run: sudo composer self-update

            - checkout

            # Dependencies
            - restore_cache:
                  key: v1-deps-{{ checksum "composer.json" }}
            - run: composer install
            - save_cache:
                  paths: [ ./vendor ]
                  key: v1-deps-{{ checksum "composer.json" }}

            # Build
            - run: wget https://github.com/box-project/box/releases/download/3.13.0/box.phar -O /tmp/box.phar
            - run: php /tmp/box.phar build

            # Test
            - run: build/insight.phar list

workflows:
    version: 2
    test:
        jobs:
            - tests-php-cs
            - tests-phpunit:
                  matrix:
                      parameters:
                          php-version: ['7.1', '7.2', '7.3', '7.4', '8.0']
            - release:
                  requires: [tests-phpunit]
                  # filters:
                      #     branches:
                  #   only: ['master']
